---
title: "Non-Renewable Energy Production in the United States"
author: "Kevin Havis"
format: 
  html:
    code-fold: true
    theme: cosmo
    embed-resources: true
    fig-dpi: 150
jupyter: python3
---

While renewable energy sources are gaining traction, non-renewable energy production remains a significant component of the United States' energy landscape. This heavy reliance on fossil fuels creates an unbalanced landscape of energy production across the country, potential weak points of energy security.

The immediately available observation shows how much Texas dominates non-renewable energy production, particularly in oil and natural gas. Other states like Wyoming and West Virginia also contribute significantly, primarily through coal production. In contrast, states in the Northeast and West Coast have relatively low non-renewable energy production, reflecting their greater emphasis on renewable energy sources.

```{python}
import pandas as pd
import plotly.graph_objects as go
state_to_code = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
}

# Load data
df = pd.read_csv(r"state_energy_production.csv")
df.drop(columns=["Demography", "Supply & Distribution", "Production"], inplace=True)

# Clean columnn
df["state_name"] = df["State Code"].map({v: k for k, v in state_to_code.items()})
# Set up column for hover text in viz
df["hover_text"] = (
    df["state_name"]
    + "<br>"
    + "Total Energy Production (trillion BTUs): "
    + df["Total Energy (trillion Btu)"].astype(str)
    + "<br>"
    + "Crude Oil (thousand barrels per day): "
    + df["Crude Oil (thousand barrels per day)"].astype(str)
    + "<br>"
    + "Natural Gas (million cubic feet): "
    + df["Natural Gas - Marketed (million cu ft)"].astype(str)
    + "<br>"
    + "Coal (short tons): "
    + df["Coal (thousand short tons)"].astype(str)
)
# Visualization
fig = go.Figure()

fig.add_trace(
    go.Choropleth(
        locations=df["State Code"],  # Uses the state code to get the graphic to render
        z=df["Total Energy (trillion Btu)"],  # Intensity by federal funding
        locationmode="USA-states",
        text=df["hover_text"],
        showscale=True,
        hovertemplate="%{text}<extra></extra>",
    )
)

fig.update_layout(
    title=dict(
        text="United States Non-Renewable Energy Production by State",
    ),
    geo=dict(scope="usa"),
    width=800,  # Wider to accommodate multiple colorbars
    height=600,
)

fig.show()
```